export {default as facebook} from './facebook.png'
export {default as instagram} from './instagram.png'
export {default as linkedin} from './linkedin.png'
export {default as telegram} from './telegram.png'
export {default as twitter} from './twitter.png'
export {default as youtube} from './youtube.png'
